# Site settings
#title: A blog about lorem ipsum dolor sit amet
#description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Clovis Olivier
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: QA Manager
email: clovis.olivier@gmail.com
#twitter_username: lorem_ipsum
github_username:  https://github.com/clovisolivier
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

# Welcome to Jekyll!
#

# Site settings
title: Clovis Olivier
description: |
  Another fine responsive
  site template freebie
  crafted by [HTML5 UP](http://html5up.net)
owner: Clovis Olivier # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: clovis.olivier@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clovisolivier.github.io/" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  email: clovis.olivier@gmail.com
  github: https://github.com/clovisolivier
  linkedin: https://linkedin.com/in/clovisolivier
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:
# Build settings
markdown: kramdown
#sass:
#  style: compressed
